config/routes.rb
Hvz::Application.routes.draw do
  resources :games

  root :to => 'Clearance::Sessions#new'
end

app/models/game.rb
class Game < ActiveRecord::Base
  belongs_to :user
end

app/models/player.rb
class Player < ActiveRecord::Base
  include ActiveRecord::Transitions

  state_machine do
    state :human
    state :original_zombie
    state :zombie, :enter => lambda {|player| player.killed_at = Time.now }

    event :killed do
      transitions :to => :zombie, :from => [:human]
    end

    event :revealed! do
      transitions :to => :zombie, :from => [:original_zombie]
    end
  end

  def kill(other_player)
    if human? || !other_player.human?
      false
    else
      other_player.killed!
      self.last_fed_at = Time.now
      true
    end
  end

  def public_kills
    if original_zombie?
      0
    else
      kills_count || 0
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  include Clearance::User

  has_many :games
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Authentication
  protect_from_forgery
end

app/controllers/games_controller.rb
class GamesController < InheritedResources::Base
  before_filter :authenticate

  protected

  def begin_of_association_chain
    current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/body_class_helper.rb
module BodyClassHelper
  # TODO: move this into a gem/plugin
  def body_class
    qualified_controller_name = controller.controller_path.gsub('/','-')
    "#{qualified_controller_name} #{qualified_controller_name}-#{controller.action_name}"
  end
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/edit.html.haml
%h1 Edit #{@game.name}

= semantic_form_for @game do |f|
  = f.inputs do
    = f.input :name
    = f.input :starts_at, :as => :string
    = f.input :ends_at, :as => :string
  = f.buttons do
    = f.commit_button

app/views/games/index.html.haml
%h1 Your games

%ul
  - @games.each do |game|
    = link_to game.name, game

app/views/games/new.html.haml
%h1 Create a game

= semantic_form_for @game do |f|
  = f.inputs do
    = f.input :name
  = f.buttons do
    = f.commit_button

app/views/games/show.html.haml
%h1
  = @game.name

%dl

  %dt
    Starts at:
  %dd#starts-at
    - if @game.starts_at
      = @game.starts_at.to_s :descriptive
    - else
      None set

  %dt
    Ends at:
  %dd#ends-at
    - if @game.ends_at
      = @game.ends_at.to_s :descriptive
    - else
      None set

= link_to "Edit", edit_game_path(@game)

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta http-equiv="Content-type" content="text/html; charset=utf-8" />
  <title>hvz</title>
  <%= stylesheet_link_tag :flutie, 'screen', :media => 'all', :cache => true %>
  <%= csrf_meta_tag %>
</head>
<body class="<%= body_class %>">
  <div id="header">
    <% if signed_in? -%>
      <%= link_to "Sign out", sign_out_path, :method => :delete %>
    <% else -%>
      <%= link_to "Sign in", sign_in_path %>
    <% end -%>
  </div>
  <%= render :partial => 'shared/flashes' -%>
  <%= yield %>
  <%= render :partial => 'shared/javascript' %>
</body>
</html>

app/views/shared/_flashes.html.erb
<div id="flash">
  <% flash.each do |key, value| -%>
    <div id="flash_<%= key %>"><%=h value %></div>
  <% end -%>
</div>

app/views/shared/_javascript.html.erb
<%= javascript_include_tag 'jquery', 'jquery-ui', 'prefilled_input',  :cache => true %>
<%= yield :javascript %>